# Datatypes

### Primitive Data Types:

 These data types are built-in or predefined data types and can be used directly by the user to declare variables. example: int, char , float, bool etc. Primitive data types available in C++ are: 
* Integer
* Character
* Boolean
* Floating Point
* Double Floating Point
* Valueless or Void
* Wide Character

------
### Derived Data Types:

 The data-types that are derived from the primitive or built-in datatypes are referred to as Derived Data Types. These can be of four types namely: 

* Function
* Array
* Pointer
* Reference


--------------------
### Abstract or User-Defined Data Types:

 These data types are defined by user itself. Like, defining a class in C++ or a structure. C++ provides the following user-defined datatypes: 

* Class
* Structure
* Union
* Enumeration
* Typedef defined DataType


-----------------

In [4]:
// C++ program to sizes of data types
#include<iostream>
using namespace std;
 

cout << "Size of char : " << sizeof(char)
    << " byte" << endl;
cout << "Size of int : " << sizeof(int)
    << " bytes" << endl;
cout << "Size of short int : " << sizeof(short int)
    << " bytes" << endl;
cout << "Size of long int : " << sizeof(long int)
    << " bytes" << endl;
cout << "Size of signed long int : " << sizeof(signed long int)
    << " bytes" << endl;
cout << "Size of unsigned long int : " << sizeof(unsigned long int)
    << " bytes" << endl;
cout << "Size of float : " << sizeof(float)
    << " bytes" <<endl;
cout << "Size of double : " << sizeof(double)
    << " bytes" << endl;
cout << "Size of wchar_t : " << sizeof(wchar_t)
       << " bytes" <<endl;
     


Size of char : 1 byte
Size of int : 4 bytes
Size of short int : 2 bytes
Size of long int : 8 bytes
Size of signed long int : 8 bytes
Size of unsigned long int : 8 bytes
Size of float : 4 bytes
Size of double : 8 bytes
Size of wchar_t : 4 bytes


@0x7fc00d593ba0

| Data Type	            |  Size (in bytes)	  |Range                         |
| -----------           | ------------------- | ---------------------------- |
| short int	            | 2	                  | -32,768 to 32,767            |
| unsigned short int    | 2	                  |  0 to 65,535                 |
| unsigned int	        | 4	                  | 0 to 4,294,967,295           | 
| int	                |4	                  |-2,147,483,648 to 2,147,483,647|
long int	4	-2,147,483,648 to 2,147,483,647
unsigned long int	4	0 to 4,294,967,295
long long int	8	-(2^63) to (2^63)-1
unsigned long long int	8	0 to 18,446,744,073,709,551,615
signed char	1	-128 to 127
unsigned char	1	0 to 255
float	4	 
double	8	 
long double	12	 
wchar_t	2 or 4	1 wide character

# What happen when we exceed valid range of built-in data types in C++?

https://www.geeksforgeeks.org/happen-exceed-valid-range-built-data-types-c/

 **Consider the below programs.** 

1) Program to show what happens when we cross range of ‘char’ : 

In [1]:
// C++ program to demonstrate
// the problem with 'char'
#include <iostream>

using namespace std;


for (char a = 0; a <= 225; a++)
    cout << a;


input_line_9:3:20: warning: comparison of constant 225 with expression of type 'char' is always true [-Wtautological-constant-out-of-range-compare]
for (char a = 0; a <= 225; a++)
                 ~ ^  ~~~


**REASON:**
a is declared as char. Here the loop is working from 0 to 225. So, it should print from 0 to 225, then stop. But it will generate a infinite loop. The reason for this is the valid range of character datatype is -128 to 127. When ‘a’ become 128 through a++, the range is exceeded and as a result the first number from negative side of the range (i.e. -128) gets assigned to a. As a result of this ‘a’ will never reach at point 225. so it will print the infinite series of character.

2) Program to show what happens when we cross range of ‘bool’ : 
 

In [1]:
// C++ program to demonstrate
// the problem with 'bool'
#include <iostream>

using namespace std;

	// declaring Boolean
	// variable with true value
	bool a = true;

	for (a = 1; a <= 5; a++)
		cout << a;



input_line_9:6:23: warning: incrementing expression of type bool is deprecated and incompatible with C++17 [-Wdeprecated-increment-bool]
        for (a = 1; a <= 5; a++)
                            ~^
input_line_9:6:16: warning: comparison of constant 5 with expression of type 'bool' is always true [-Wtautological-constant-out-of-range-compare]
        for (a = 1; a <= 5; a++)
                    ~ ^  ~


**REASON:** his code will print ‘1’ infinite time because here ‘a’ is declared as ‘bool’ and it’s valid range is 0 to 1. And for a Boolean variable anything else than 0 is 1 (or true). When ‘a’ tries to become 2 (through a++), 1 gets assigned to ‘a’. The condition a<=5 is satisfied and the control remains with in the loop. See this for Bool data type.

3) Program to show what happens when we cross range of ‘short’ : 
Note that short is short for short int. They are synonymous. short, short int, signed short, and signed short int are all the same data-type. 

In [1]:
// C++ program to demonstrate
// the problem with 'short'
#include <iostream>

using namespace std;


// declaring short variable
short a;

for (a = 32767; a < 32770; a++)
    cout << a << "\n";



input_line_9:5:19: warning: comparison of constant 32770 with expression of type 'short' is always true [-Wtautological-constant-out-of-range-compare]
for (a = 32767; a < 32770; a++)
                ~ ^ ~~~~~


**REASON:** Will this code print ‘a’ till it becomes 32770? Well the answer is indefinite loop, because here ‘a’ is declared as a short and its valid range is -32768 to +32767. When ‘a’ tries to become 32768 through a++, the range is exceeded and as a result the first number from negative side of the range(i.e. -32768) gets assigned to a. Hence the condition “a < 32770” is satisfied and control remains within the loop.